version: '3.8'
services:
  db:
    image: mysql:8.0       
    container_name: SKVS
    environment:
      - MYSQL_ROOT_PASSWORD=supersecret
      - MYSQL_DATABASE=SKVS
      - MYSQL_USER=skvs_user          # Naujas vartotojas (nebūtinai root)
      - MYSQL_PASSWORD=skvs_password  # Slaptažodis naujam vartotojui
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
